name: Build and Push image to registry

on:
  push:
    tags:
    - v*.*.*
    branches:
      - dev 
    paths:
      - '**.*'
 
  release:
    types: 
    - published
    
jobs:
# Workflow defines what trigger an action and uses action that is suitable for the process
  trigger-build:
    if: ${{ github.event_name == 'push'  }}
    uses: wgall/cloudrun_laravel_cicd/.github/workflows/main.yml@main
    secrets: inherit
  versioning:
    if: ${{ github.event_name == 'release' && github.event.release.prerelease }}
    uses: wgall/cloudrun_laravel_cicd/.github/workflows/versioning.yml@main
    secrets: inherit
  production: 
    if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
    uses: wgall/cloudrun_laravel_cicd/.github/workflows/production.yml@main
    secrets: inherit
